source 'https://rubygems.org'

gem 'rails', '5.2.0'
gem 'rack', '1.6.0'
gem 'devise', '3.5.2'
gem 'nokogiri', '1.8.1'
gem 'paperclip', '5.3.0'
gem 'loofah', '2.2.3'
gem 'rails-html-sanitizer', '1.0.4'
gem 'sprockets', '3.7.1'
gem 'kaminari', '0.17.0'
gem 'json', '1.8.1'

gem 'sqlite3'
